FROM golang:1.24-alpine AS builder
RUN apk add --no-cache git
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
RUN go install github.com/air-verse/air@latest

FROM golang:1.24-alpine
RUN apk add --no-cache git
WORKDIR /app
COPY --from=builder /go/bin/air /usr/local/bin/air
COPY go.mod go.sum ./
RUN go mod download

EXPOSE 8080
CMD ["air", "-c", ".air.toml"]
