// GENERATED by scripts/design-tokens.mjs from design/tokens.json — do not edit by hand.
// Dark-theme palette and brand colours as hex, for the release-video title cards.

export const palette = {
  background: '#14161a',
  card: '#1d1f26',
  foreground: '#dfe6ec',
  mutedForeground: '#7d8a9b',
  border: '#343842',
  blue: '#61a6fa',
  coral: '#de6254',
} as const
