{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "jarvis.fullname" . }}
  labels:
    {{- include "jarvis.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "jarvis.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - ports:
        - port: 8080
          protocol: TCP
      {{- with .Values.networkPolicy.ingress.from }}
      from:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- if or .Values.networkPolicy.egress.allowDns .Values.networkPolicy.egress.rules }}
  egress:
    {{- if .Values.networkPolicy.egress.allowDns }}
    - ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
    {{- end }}
    {{- with .Values.networkPolicy.egress.rules }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- else }}
  egress: []
  {{- end }}
{{- end }}
