{{- if not .Values.database.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jarvis.fullname" . }}
  labels:
    {{- include "jarvis.labels" . | nindent 4 }}
type: Opaque
stringData:
  dsn: {{ .Values.database.dsn | quote }}
  {{- if and (ne .Values.auth.provider "none") (not .Values.auth.existingSecret) .Values.auth.secretKey }}
  secret-key: {{ .Values.auth.secretKey | quote }}
  {{- end }}
  {{- if and (eq .Values.auth.provider "oidc") (not .Values.auth.existingSecret) .Values.auth.oidc.clientSecret }}
  oidc-client-secret: {{ .Values.auth.oidc.clientSecret | quote }}
  {{- end }}
{{- end }}
