#!/usr/bin/env node
// Generates every colour-token file from design/tokens.json (the single source).
//
//   node scripts/design-tokens.mjs           write the generated files
//   node scripts/design-tokens.mjs --check   exit 1 if any of them is stale
//
// Outputs (never edit by hand):
//   frontend/src/generated/tokens.css                app: Tailwind @theme + [data-theme="light"]
//   website/.vitepress/theme/generated-tokens.css    docs: VitePress variables + the coral accent
//   frontend/e2e/video/generated-theme.ts            videos: hex constants (dark theme + brand)
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs'
import { dirname, join, relative } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const tokens = JSON.parse(readFileSync(join(ROOT, 'design/tokens.json'), 'utf8'))
const check = process.argv.includes('--check')
const BANNER = 'GENERATED by scripts/design-tokens.mjs from design/tokens.json — do not edit by hand.'

const hsl = (v) => {
  const [c, a] = v.split('/').map((s) => s.trim())
  return a === undefined ? `hsl(${c})` : `hsl(${c} / ${a})`
}
const hex = (v) => {
  const [h, s, l] = v.split('/')[0].trim().split(/\s+/).map((x) => parseFloat(x))
  const S = s / 100, L = l / 100
  const k = (n) => (n + h / 30) % 12
  const a = S * Math.min(L, 1 - L)
  const f = (n) => L - a * Math.max(-1, Math.min(k(n) - 3, 9 - k(n), 1))
  return '#' + [f(0), f(8), f(4)].map((x) => Math.round(x * 255).toString(16).padStart(2, '0')).join('')
}
const resolve = (theme, v) => (v.startsWith('@') ? tokens.app[theme][v.slice(1)] ?? tokens.app.dark[v.slice(1)] : v)

const lines = (obj, prefix, indent = '  ') =>
  Object.entries(obj).map(([k, v]) => `${indent}--${prefix}${k}: ${hsl(v)};`)

// ── app ───────────────────────────────────────────────────────────────────────
const app = `/* ${BANNER} */

@theme {
  /* Dark mode (default)
   * Depth chain: background(9%) → card/header(13-14%) → input(16%) → muted(19%) → accent(21%) → border(23%)
   * Header is lifted further above background than the chain's step size (9→14, not 9→11) so the
   * toolbar reads as a distinct raised surface instead of nearly blending into the page.
   * Low saturation (12-15%) avoids the "electric navy" feeling of high-sat near-black surfaces.
   * --color-control is the edge of text fields/selects (>= 3:1 against every surface, WCAG 1.4.11);
   * --color-border stays the quiet edge for cards/header/tables.
   */
${lines(tokens.app.dark, 'color-').join('\n')}

  /* Radius roles: compact (dense chips/cells), control (fields, buttons), surface (cards, panels),
   * overlay (dialogs, floating layers), pill (badges, dots). Utilities: rounded-control, … */
${Object.entries(tokens.radius).map(([k, v]) => `  --radius-${k}: ${v};`).join('\n')}
}

[data-theme="light"] {
  /*
   * Depth chain: background(94%) → muted(92%) → accent(89%) → border(83%)
   * Surface elevation: background(94%) → header(99%) → card(100%)
   * Consistent hue: 220 (cool blue-gray), saturation 11-15%. Severity colours are not overridden.
   */
${lines(tokens.app.light, 'color-').join('\n')}
}
`

// ── site ──────────────────────────────────────────────────────────────────────
const siteBlock = (theme) => {
  const t = tokens.site[theme]
  const out = Object.entries(t).map(([k, v]) => `  --vp-c-${k}: ${hsl(resolve(theme, v))};`)
  out.push(`  --jarvis-coral: ${hsl(tokens.brand.coral[theme])};`)
  return out.join('\n')
}
const site = `/* ${BANNER} */

/* Coral is the owl's right eye: a sparing accent, never a status colour. */
:root {
${siteBlock('light')}
}

.dark {
${siteBlock('dark')}
}
`

// ── video ─────────────────────────────────────────────────────────────────────
const d = tokens.app.dark
const video = `// ${BANNER}
// Dark-theme palette and brand colours as hex, for the release-video title cards.

export const palette = {
  background: '${hex(d.background)}',
  card: '${hex(d.card)}',
  foreground: '${hex(d.foreground)}',
  mutedForeground: '${hex(d['muted-foreground'])}',
  border: '${hex(d.border)}',
  blue: '${hex(d.link)}',
  coral: '${hex(tokens.brand.coral.dark)}',
} as const
`

const outputs = {
  'frontend/src/generated/tokens.css': app,
  'website/.vitepress/theme/generated-tokens.css': site,
  'frontend/e2e/video/generated-theme.ts': video,
}

const stale = []
for (const [rel, content] of Object.entries(outputs)) {
  const path = join(ROOT, rel)
  if (check) {
    if (!existsSync(path) || readFileSync(path, 'utf8') !== content) stale.push(rel)
  } else {
    mkdirSync(dirname(path), { recursive: true })
    writeFileSync(path, content)
    console.log('wrote', relative(ROOT, path))
  }
}
if (check && stale.length) {
  console.error('stale generated design tokens: ' + stale.join(', ') + ' — run: node scripts/design-tokens.mjs')
  process.exit(1)
}
